import 'package:flutter/material.dart';

const textInputDecoration=InputDecoration(
  border: OutlineInputBorder(
    borderRadius: BorderRadius.all(Radius.circular(28.0)),
  ),
  fillColor: Colors.white,
  filled: true,
  isDense: true,
  contentPadding: EdgeInsets.all(8.0)
);

var buttonStyleSignIn= ButtonStyle(
  fixedSize: WidgetStateProperty.all<Size>(const Size(250.0, 50)),
  backgroundColor: WidgetStateProperty.all<Color>(Colors.white),
  shape: WidgetStateProperty.all<RoundedRectangleBorder>(RoundedRectangleBorder(
    borderRadius: BorderRadius.circular(28.0),
  )),
  foregroundColor: WidgetStateProperty.all<Color>(Color(0xFF3F51B5)),
  side: WidgetStateProperty.all<BorderSide>(
      const BorderSide(color: Color(0xFF3F51B5), width: 2.0)),
);

const List<String> courses = [
  // Engineering & Technology
  "B.Tech CSE",
  "B.Tech IT",
  "B.Tech ECE",
  "B.Tech EEE",
  "B.Tech Mechanical",
  "B.Tech Civil",
  "B.Tech AI & ML",
  "B.Tech Data Science",
  "B.Tech Biotechnology",
  "B.Tech Aerospace",
  "B.Tech Automobile",
  "B.Tech Chemical",
  "B.Tech Mechatronics",
  "M.Tech CSE",
  "M.Tech ECE",
  "M.Tech Mechanical",
  "M.Tech Civil",
  "M.Tech Data Science",
  "M.Tech AI & Robotics",

  // Computer Applications
  "BCA",
  "MCA",

  // Science
  "B.Sc Computer Science",
  "B.Sc Mathematics",
  "B.Sc Physics",
  "B.Sc Chemistry",
  "B.Sc Statistics",
  "B.Sc Electronics",
  "B.Sc Biotechnology",
  "B.Sc Microbiology",
  "B.Sc Zoology",
  "B.Sc Botany",
  "M.Sc Computer Science",
  "M.Sc Mathematics",
  "M.Sc Physics",
  "M.Sc Chemistry",
  "M.Sc Statistics",
  "M.Sc Biotechnology",
  "M.Sc Microbiology",
  "M.Sc Zoology",
  "M.Sc Botany",

  // Management
  "MBA",
  "BBA",
  "PGDM",

  // Medical & Health
  "MBBS",
  "BDS",
  "BAMS",
  "BHMS",
  "BPT (Physiotherapy)",
  "B.Pharm",
  "M.Pharm",
  "Nursing (B.Sc Nursing)",
  "MD Medicine",
  "MS Surgery",

  // Arts & Humanities
  "BA English",
  "BA History",
  "BA Political Science",
  "BA Psychology",
  "BA Sociology",
  "BA Philosophy",
  "BA Journalism & Mass Comm",
  "BA Linguistics",
  "MA English",
  "MA History",
  "MA Political Science",
  "MA Psychology",
  "MA Sociology",
  "MA Philosophy",
  "MA Journalism",

  // Law
  "LLB",
  "LLM",

  "other"
];

const List<String> subjects = [
  "Mathematics",
  "English",
  "Hindi",
  "Science",
  "Social Science",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "Economics",
  "Business Studies",
  "Accountancy",
  "History",
  "Geography",
  "Political Science",
  "Sociology",
  "Psychology",
  "Environmental Science",
  "Physical Education",
  "General Knowledge",
  // Computer Science & IT
  "Programming in C",
  "C++",
  "Java",
  "Python",
  "Data Structures",
  "Algorithms",
  "Operating Systems",
  "Computer Networks",
  "Database Management Systems (DBMS)",
  "Software Engineering",
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Cloud Computing",
  "Cyber Security",
  "Compiler Design",
  "Computer Graphics",
  "Theory of Computation",
  "Big Data Analytics",
  "Web Development",
  "Mobile App Development",

  // Core Engineering
  "Engineering Mathematics I",
  "Engineering Mathematics II",
  "Engineering Physics",
  "Engineering Chemistry",
  "Basic Electrical Engineering",
  "Electronics Engineering",
  "Signals and Systems",
  "Digital Logic Design",
  "Microprocessors",
  "Control Systems",
  "Thermodynamics",
  "Fluid Mechanics",
  "Strength of Materials",
  "Structural Analysis",
  "Manufacturing Processes",
  "Automobile Engineering",
  "Robotics",
  "Aerospace Engineering",

  // Science
  "Physics",
  "Quantum Mechanics",
  "Classical Mechanics",
  "Electrodynamics",
  "Nuclear Physics",
  "Organic Chemistry",
  "Inorganic Chemistry",
  "Physical Chemistry",
  "Analytical Chemistry",
  "Botany",
  "Zoology",
  "Genetics",
  "Microbiology",
  "Biotechnology",
  "Biochemistry",
  "Environmental Science",
  "Statistics",
  "Probability",
  "Linear Algebra",

  // Management & Commerce
  "Principles of Management",
  "Business Economics",
  "Managerial Accounting",
  "Financial Management",
  "Marketing Management",
  "Human Resource Management",
  "Operations Management",
  "Business Law",
  "Entrepreneurship",
  "Strategic Management",
  "B.Com General",
  "B.Com Accounting & Finance",
  "B.Com Banking & Insurance",
  "B.Com Economics",
  "BBA",
  "M.Com",

  // Medical & Health Sciences
  "Anatomy",
  "Physiology",
  "Biochemistry",
  "Pathology",
  "Pharmacology",
  "Microbiology (Medical)",
  "Community Medicine",
  "Forensic Medicine",
  "Surgery",
  "Medicine",
  "Pediatrics",
  "Orthopedics",
  "Gynecology & Obstetrics",

  // Arts & Humanities
  "History of India",
  "World History",
  "Political Science",
  "International Relations",
  "Public Administration",
  "Sociology",
  "Anthropology",
  "Philosophy",
  "Psychology",
  "Education",
  "English Literature",
  "Linguistics",
  "Journalism",
  "Mass Communication",
  "Cultural Studies",

  "other"
];
